### ISSUE TITLE
Broken on 2019.1's new PM

### ISSUE THREAD

**Issue by 0lento** [mob-sakai/UpmGitExtension#13]
2019.1 is still in beta but they've changed the PM structure making this extension to not work properly there.

Just giving a heads up about it.

**Comment by mob-sakai** [comment]
Hi @0lento 
OMG... X(

**Comment by mob-sakai** [comment]
I'll fix it as soon as possible.

**Comment by Lasser01** [comment]
Had a quick look, it is due to the change of UI. I found a quick fix to tie me over until it's properly fixed. 
Note: The UI is a bit funny, due to the new package manager UI.

Sorry, if you find this annoying, just wanted to help. 

But a quick fix to get it working is to change:
`
_gitDetailActoins = asset.CloneTree().Q("detailActions"); gitDetailActoins.styleSheets.Add(EditorGUIUtility.Load(StylePath) as StyleSheet);
` 

To:

` _gitDetailActoins = asset.CloneTree().Q("detailActions");
  _gitDetailActoins.styleSheets.Add(EditorGUIUtility.Load(StylePath) as StyleSheet);
`

The lines are at 141 and 142 UpmGitExtensionUI.cs

And 

`_detailControls = parent.parent.Q("detailsControls");`

To:

`
_detailControls = parent.parent.parent.parent.Q("packageToolBar");
`

At the lines at 155 UpmGitExtensionUI.cs

And

`
_detailControls.Q ("updateCombo").Insert (1,_updateButton);
_detailControls.Q ("updateDropdownContainer").Add(_versionPopup);
`

To:

`_detailControls.Q ("rightItems").Insert (1,_updateButton);
_detailControls.Q ("rightItems").Add(_versionPopup);
`

These lines are found at: 167 and 168  UpmGitExtensionUI.cs

And here to fix the position of the version dropdown:
`
_versionPopup = new Button (PopupVersions) { text = "hoge", style = { marginLeft = -4, marginRight = -3, marginTop = -3, marginBottom = -3, }, };`
To:

`_versionPopup = new Button (PopupVersions) { text = "hoge", style = { marginLeft = 0, marginRight = 10, marginTop = -3, marginBottom = -3, }, };`

Line 162 UpmGitExtensionUI.cs

**Comment by mob-sakai** [comment]
Thanks a lot, @Lasser01 !
I fixed the issue. ;)

![image](https://user-images.githubusercontent.com/12690315/52464583-d17e3280-2bbe-11e9-83d9-454d100c0dd4.png)
