### ISSUE TITLE
UPM Doesn't show available versions for Private Azure DevOps Repo

### ISSUE THREAD

**Issue by TCROC** [mob-sakai/UpmGitExtension#85]
UpmGitExtensionVersion: "1.1.0-preview.12-upm"

Other versions to install are not displayed after closing the Unity Project and opening it back up for a Private Azure DevOps repo.

First Install:

![image](https://user-images.githubusercontent.com/24307049/76152252-56ba6c00-608b-11ea-8387-cfbaf5ffc8fe.png)

![image](https://user-images.githubusercontent.com/24307049/76152272-a26d1580-608b-11ea-9c32-8dd0102638a3.png)

Everything appears correctly.

After closing and reopening Unity, the available versions no longer display.  Even if refreshing the UPM.

![image](https://user-images.githubusercontent.com/24307049/76152339-7e5e0400-608c-11ea-8c5f-6c901aa6bba2.png)

The UPM versions appear correctly though.  Just the Private Azure DevOps repos that are the problem.

**Comment by mob-sakai** [comment]
@TCROC 
Hmm...
It doesn't happen in my environment.

- Unity 2019.3.0f6
- UpmGitExtension 1.0.0-preview.12
- Azure Dev Ops Repos (private)
- ssh protocol & https (with access token) protocol

### Questions

**Question:** Can you clone it with terminal / prompt?

```
git clone {your_repo_url}
```

**Hint:** If you add `UGE_LOG` as a script define symbol, a detailed log will be displayed on the console.

![image](https://user-images.githubusercontent.com/12690315/76189016-ecd1cc00-621c-11ea-8f7b-cf7aff276f7d.png)

![image](https://user-images.githubusercontent.com/12690315/76189176-5fdb4280-621d-11ea-851a-7e3183af9e5d.png)

**Comment by TCROC** [comment]
Idk what the issue was, but this no longer appears to be an issue.  Things seem to be working correctly.  Maybe I just had slow internet that day.  I'll close this for now as it doesn't seem to be an issue.

**Comment by hannesdelbeke** [comment]
@TCROC 
hi, sorry if this is not the appropriate place to post but not sure where else to post this.

how do you get versioning to work in azure git repo with this extension?

**Comment by TCROC** [comment]
> @TCROC
> hi, sorry if this is not the appropriate place to post but not sure where else to post this.
> 
> how do you get versioning to work in azure git repo with this extension?

Could you open up a separate issue with the struggles you are having?  Then we can help you get it set up correctly or fix the bug if it is an issue with UPM. :)

**Comment by hannesdelbeke** [comment]
created one here:
https://github.com/mob-sakai/UpmGitExtension/issues/108

upon more testing i realized loading a package from git repo on azure works fine
but it doesn't work with subfolders

**Comment by TCROC** [comment]
> created one here:
> #108
> 
> upon more testing i realized loading a package from git repo on azure works fine
> but it doesn't work with subfolders

Depending on the version of unity that you are using, I think sub folders are supported.  I think they were added in Unity 2020 but I'm not sure.

**Comment by hannesdelbeke** [comment]
that is the issue
my unity version does support subfolders through the http "?path=/" addon
![image](https://user-images.githubusercontent.com/3758308/105078816-6f0a5e00-5a86-11eb-9411-b9d8c2aaa0f8.png)
it is even documented on [the unity docs](https://docs.unity3d.com/Manual/upm-git.html )

the subfolders work fine when i add them manually to the manifest
but it doesn't work when trying to do it trough this git extension tool

and when i add my package manually, it shows up in the package manager
but there is no update version button
![image](https://user-images.githubusercontent.com/3758308/105078700-45513700-5a86-11eb-9def-c85b79995c1b.png)

this extension adds an update version button to any other git repo i have that do not use subfolders

actually on looking into it further it's not just missing, it's inconsistent since it does show here, and this is a fork of this repo moved to a subfolder. then setup manually through the manifest
![image](https://user-images.githubusercontent.com/3758308/105079035-bd1f6180-5a86-11eb-81c1-e77de54d551f.png)

**Comment by hannesdelbeke** [comment]
when not installing in a subfolder i get a dropdown arrow and the option to choose version
![image](https://user-images.githubusercontent.com/3758308/105079526-74b47380-5a87-11eb-88e4-e349f6acb826.png)
