### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by basstal** [mob-sakai/UpmGitExtension#94]
![image](https://user-images.githubusercontent.com/10006640/91533001-bbbb9400-e941-11ea-9c7b-6372c50a7bea.png)
should I use any proxy??
![image](https://user-images.githubusercontent.com/10006640/91533148-fb827b80-e941-11ea-96a3-d5cea2a14240.png)

**Comment by mob-sakai** [comment]
@basstal 
Sorry. I don't know much about network proxy.

Can you download the following nuget package without setting up a proxy?
```
curl -o OpenSesame.Net.Compilers.3.4.0-beta.4.zip -L https://www.nuget.org/api/v2/package/OpenSesame.Net.Compilers/3.4.0-beta.4
```

if you can download it, I should change the download URL for the package.

**Comment by basstal** [comment]
I can't visit URL https://www.nuget.org/api/v2/package/OpenSesame.Net.Compilers/3.4.0-beta.4 without proxy...

**Comment by basstal** [comment]
The problem is, I don't know how to setup the proxy when unity execute command 'curl xxxx', seems like this curl request didn't use my export proxy settings in zsh. I can download OpenSesame.Net.Compilers.3.4.0-beta.4.zip in zsh but not in unity.
![image](https://user-images.githubusercontent.com/10006640/91539485-fb877900-e94b-11ea-9928-fea4d22d5cc8.png)

**Comment by mob-sakai** [comment]
@basstal 

> The problem is, I don't know how to setup the proxy when unity execute command 'curl xxxx',
Me too.

Can you download the following nuget package without setting up a proxy?
```
curl -o OpenSesame.Net.Compilers.3.4.0-beta.4.zip -L https://github.com/mob-sakai/UpmGitExtension/files/5140976/opensesame.net.compilers.3.4.0-beta.4.zip
```

**Comment by mob-sakai** [comment]
I should use `WebClient.DownloadFile` instead of `curl` command.
However, it will lose .Net 3.5 support.

**Comment by basstal** [comment]
![image](https://user-images.githubusercontent.com/10006640/91541104-62a62d00-e94e-11ea-8b44-640deb340a36.png)
sad..

**Comment by mob-sakai** [comment]
Thank you for your help!

**Comment by FullMe7alJacke7** [comment]
Not really sure how the curl command works, but for some reason when I ran it in my project with the deform package, it some how caused Unity to say Deform's dependencies were incorrect. 
I didn't edit any other stuff prior and it was just fine before the curl command. 

I removed the Deform package as I luckily wasn't using it yet and removed relevant lines in the manifest which seems to have fixed it.
I then removed this package and all pertaining lines as well. 
Attempted to re-run said command which still failed.
I again removed the package's lines from manifest file.
Imported the repo from git using https and it worked just fine. 

Not sure if me using a VPN caused an issue or what but all is well. just thought I would put this here since the issue was opened less than 24 hours ago. 

Unity 2020.1
Windows 10
UPM Git Extension 1.3.1

**Comment by mob-sakai** [comment]
@basstal @FullMe7alJacke7 
Thanks for your help.

According to this manual, you need a launch script to set the environment variables `HTTP_PROXY` and `HTTPS_PROXY`.
https://docs.unity3d.com/2019.3/Documentation/Manual/upm-network.html

### Windows

Save the following command as `launchUnityHub.cmd` and run it.
```
@echo off
set HTTP_PROXY=http://proxy-url:port
set HTTPS_PROXY=http://proxy-url:port
start "" "C:\Program Files\Unity Hub\Unity Hub.exe"
```

### macOS

Execute the following command and run `launchUnityHub.command`.
```
echo '#!/bin/bash
export HTTP_PROXY=http://proxy-url:port
export HTTPS_PROXY=http://proxy-url:port
nohup "/Applications/Unity Hub.app/Contents/MacOS/Unity Hub" &>/dev/null &' > launchUnityHub.command
chmod +x launchUnityHub.command
```
